// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220121063229_UpdatePostModel")]
    partial class UpdatePostModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImagePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "A description of category 1",
                            Name = "Category 1",
                            ThumbnailImagePath = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "A description of category 2",
                            Name = "Category 2",
                            ThumbnailImagePath = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "A description of category 3",
                            Name = "Category 3",
                            ThumbnailImagePath = "uploads/placeholder.jpg"
                        });
                });

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImagePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Author = "admin",
                            CategoryId = 1,
                            Content = "",
                            Excerpt = "This is an excerpt for post 1",
                            IsPublished = true,
                            PublishDate = "21/01/22 06:32:29 AM",
                            ThumbnailImagePath = "/uploads/placeholder.jpg",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Author = "admin",
                            CategoryId = 1,
                            Content = "",
                            Excerpt = "This is an excerpt for post 2",
                            IsPublished = true,
                            PublishDate = "21/01/22 06:32:29 AM",
                            ThumbnailImagePath = "/uploads/placeholder.jpg",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Author = "admin",
                            CategoryId = 2,
                            Content = "",
                            Excerpt = "This is an excerpt for post 3",
                            IsPublished = true,
                            PublishDate = "21/01/22 06:32:29 AM",
                            ThumbnailImagePath = "/uploads/placeholder.jpg",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Author = "admin",
                            CategoryId = 2,
                            Content = "",
                            Excerpt = "This is an excerpt for post 4",
                            IsPublished = true,
                            PublishDate = "21/01/22 06:32:29 AM",
                            ThumbnailImagePath = "/uploads/placeholder.jpg",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Author = "admin",
                            CategoryId = 3,
                            Content = "",
                            Excerpt = "This is an excerpt for post 5",
                            IsPublished = true,
                            PublishDate = "21/01/22 06:32:29 AM",
                            ThumbnailImagePath = "/uploads/placeholder.jpg",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Author = "admin",
                            CategoryId = 3,
                            Content = "",
                            Excerpt = "This is an excerpt for post 6",
                            IsPublished = true,
                            PublishDate = "21/01/22 06:32:29 AM",
                            ThumbnailImagePath = "/uploads/placeholder.jpg",
                            Title = "Post 6"
                        });
                });

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.HasOne("Shared.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
